# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Solis Scraper"
version: "2.0.0"
slug: solis-scraper
url: https://github.com/ikkentim/homeassistant-addons
description: >-
  Scrapes data about power production from the local webpage of a Solis inverter.
arch:
  - amd64
init: false
image: ghcr.io/ikkentim/ha-{arch}-solis-scraper
options:
  Scraper:
    Instances:
    - Host: "http://IP-ADDRESS-HERE"
      Username: admin
      Password: admin
      Name: Solis Energy
      NodeId: solis
      UniqueId: solis_scraper
      Format: 1
  Mqtt:
    Host: core-mosquitto
    Username: ""
    Password: ""
    ClientId: solis_scraper
    DiscoveryPrefix: homeassistant
schema:
  Scraper:
    Instances:
    - Host: str
      Username: str
      Password: str
      Name: str
      NodeId: str
      UniqueId: str
      Format: "int(1,2)"
      ResetAfterMidnightTimeZone: "str?"
  Mqtt:
    Host: str
    Username: str
    Password: str
    ClientId: str
    DiscoveryPrefix: str
