# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Solis Scraper"
version: "1.2.0"
slug: solis-scraper
url: https://github.com/ikkentim/homeassistant-addons
description: >-
  Scrapes data about power production from the local webpage of a Solis inverter.
arch:
  - amd64
init: false
image: ghcr.io/ikkentim/ha-{arch}-solis-scraper
options:
  Scraper:
    Host: "http://IP-ADDRESS-HERE"
    Username: admin
    Password: admin
    Format: 1
  Mqtt:
    Host: core-mosquitto
    Username: ""
    Password: ""
    ClientId: solis_scraper
    DiscoveryPrefix: homeassistant
    NodeId: solis
    UniqueIdPrefix: solis_scraper
schema:
  Scraper:
    Host: str
    Username: str
    Password: str
    Format: "int(1,2)"
    ResetAfterMidnightTimeZone: "str?"
  Mqtt:
    Host: str
    Username: str
    Password: str
    ClientId: str
    DiscoveryPrefix: str
    NodeId: str
    UniqueIdPrefix: str
