# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Hello world"
version: "1.0.2"
slug: hello-world
url: https://github.com/ikkentim/homeassistant-addons
description: >-
  Just a test
arch:
  - amd64
init: false
image: ghcr.io/ikkentim/ha-{arch}-hello-world
options:
  message: "Hello world..."
schema:
  message: "str?"
